import CodeBehindOfficeEquipmentModelWizardFactory from './codeBehind/codeBehindOfficeEquipmentModelWizardFactory';

export default class OfficeEquipmentModelWizardFactory extends CodeBehindOfficeEquipmentModelWizardFactory {
}
