//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karelia.WebAPI.Controllers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karelia.WebAPI.Controllers.Properties.ActionsResources", typeof(ActionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string CarModels_CarModels_CreateCarModel {
            get {
                return ResourceManager.GetString("CarModels_CarModels_CreateCarModel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string CarModels_CarModels_EditCarModel {
            get {
                return ResourceManager.GetString("CarModels_CarModels_EditCarModel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string CarModels_CarModels_DeleteCarModel {
            get {
                return ResourceManager.GetString("CarModels_CarModels_DeleteCarModel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string CarModels_CarModels_RefreshCarModel {
            get {
                return ResourceManager.GetString("CarModels_CarModels_RefreshCarModel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string CarModels_CarModelPart_CreateCarModelPart {
            get {
                return ResourceManager.GetString("CarModels_CarModelPart_CreateCarModelPart", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string CarModels_CarModelPart_EditCarModelPart {
            get {
                return ResourceManager.GetString("CarModels_CarModelPart_EditCarModelPart", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string CarModels_CarModelPart_DeleteCarModelPart {
            get {
                return ResourceManager.GetString("CarModels_CarModelPart_DeleteCarModelPart", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string CarModels_CarModelPart_RefreshCarModelPart {
            get {
                return ResourceManager.GetString("CarModels_CarModelPart_RefreshCarModelPart", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string Cars_CarsGridBlock_CreateCar {
            get {
                return ResourceManager.GetString("Cars_CarsGridBlock_CreateCar", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string Cars_CarsGridBlock_EditCar {
            get {
                return ResourceManager.GetString("Cars_CarsGridBlock_EditCar", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Cars_CarsGridBlock_DeleteCar {
            get {
                return ResourceManager.GetString("Cars_CarsGridBlock_DeleteCar", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Cars_CarsGridBlock_RefreshCar {
            get {
                return ResourceManager.GetString("Cars_CarsGridBlock_RefreshCar", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string Cars_CarServiceDataGrid_CreateCarService {
            get {
                return ResourceManager.GetString("Cars_CarServiceDataGrid_CreateCarService", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string Cars_CarServiceDataGrid_EditCarService {
            get {
                return ResourceManager.GetString("Cars_CarServiceDataGrid_EditCarService", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Cars_CarServiceDataGrid_DeleteCarService {
            get {
                return ResourceManager.GetString("Cars_CarServiceDataGrid_DeleteCarService", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Cars_CarServiceDataGrid_RefreshCarService {
            get {
                return ResourceManager.GetString("Cars_CarServiceDataGrid_RefreshCarService", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string Cars_CarServicePart_CreateCarServicePart {
            get {
                return ResourceManager.GetString("Cars_CarServicePart_CreateCarServicePart", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string Cars_CarServicePart_EditCarServicePart {
            get {
                return ResourceManager.GetString("Cars_CarServicePart_EditCarServicePart", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Cars_CarServicePart_DeleteCarServicePart {
            get {
                return ResourceManager.GetString("Cars_CarServicePart_DeleteCarServicePart", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Cars_CarServicePart_RefreshCarServicePart {
            get {
                return ResourceManager.GetString("Cars_CarServicePart_RefreshCarServicePart", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string Cars_CarServiceWork_CreateCarServiceWork {
            get {
                return ResourceManager.GetString("Cars_CarServiceWork_CreateCarServiceWork", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string Cars_CarServiceWork_EditCarServiceWork {
            get {
                return ResourceManager.GetString("Cars_CarServiceWork_EditCarServiceWork", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Cars_CarServiceWork_DeleteCarServiceWork {
            get {
                return ResourceManager.GetString("Cars_CarServiceWork_DeleteCarServiceWork", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Cars_CarServiceWork_RefreshCarServiceWork {
            get {
                return ResourceManager.GetString("Cars_CarServiceWork_RefreshCarServiceWork", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string Works_Cars_CreateCar {
            get {
                return ResourceManager.GetString("Works_Cars_CreateCar", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string Works_Cars_EditCar {
            get {
                return ResourceManager.GetString("Works_Cars_EditCar", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Works_Cars_DeleteCar {
            get {
                return ResourceManager.GetString("Works_Cars_DeleteCar", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Works_Cars_RefreshCar {
            get {
                return ResourceManager.GetString("Works_Cars_RefreshCar", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string Works_Services_CreateService {
            get {
                return ResourceManager.GetString("Works_Services_CreateService", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string Works_Services_EditService {
            get {
                return ResourceManager.GetString("Works_Services_EditService", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Works_Services_DeleteService {
            get {
                return ResourceManager.GetString("Works_Services_DeleteService", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Works_Services_RefreshService {
            get {
                return ResourceManager.GetString("Works_Services_RefreshService", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string Tasks_MainTaskGrid_CreateMainTask {
            get {
                return ResourceManager.GetString("Tasks_MainTaskGrid_CreateMainTask", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string Tasks_MainTaskGrid_EditMainTask {
            get {
                return ResourceManager.GetString("Tasks_MainTaskGrid_EditMainTask", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Tasks_MainTaskGrid_DeleteMainTask {
            get {
                return ResourceManager.GetString("Tasks_MainTaskGrid_DeleteMainTask", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Tasks_MainTaskGrid_RefreshMainTask {
            get {
                return ResourceManager.GetString("Tasks_MainTaskGrid_RefreshMainTask", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string Tasks_SubTaskGrid_CreateSubTask {
            get {
                return ResourceManager.GetString("Tasks_SubTaskGrid_CreateSubTask", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string Tasks_SubTaskGrid_EditSubTask {
            get {
                return ResourceManager.GetString("Tasks_SubTaskGrid_EditSubTask", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Tasks_SubTaskGrid_DeleteSubTask {
            get {
                return ResourceManager.GetString("Tasks_SubTaskGrid_DeleteSubTask", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Tasks_SubTaskGrid_RefreshSubTask {
            get {
                return ResourceManager.GetString("Tasks_SubTaskGrid_RefreshSubTask", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string ModelEquipments_ModelEquipmentGrid_CreateEquipmentModel {
            get {
                return ResourceManager.GetString("ModelEquipments_ModelEquipmentGrid_CreateEquipmentModel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string ModelEquipments_ModelEquipmentGrid_EditEquipmentModel {
            get {
                return ResourceManager.GetString("ModelEquipments_ModelEquipmentGrid_EditEquipmentModel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ModelEquipments_ModelEquipmentGrid_DeleteEquipmentModel {
            get {
                return ResourceManager.GetString("ModelEquipments_ModelEquipmentGrid_DeleteEquipmentModel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string ModelEquipments_ModelEquipmentGrid_RefreshEquipmentModel {
            get {
                return ResourceManager.GetString("ModelEquipments_ModelEquipmentGrid_RefreshEquipmentModel", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Office_OfficeDataGrid_CreateAdress {
            get {
                return ResourceManager.GetString("Office_OfficeDataGrid_CreateAdress", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Office_OfficeDataGrid_EditAdress {
            get {
                return ResourceManager.GetString("Office_OfficeDataGrid_EditAdress", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Office_OfficeDataGrid_DeleteAdress {
            get {
                return ResourceManager.GetString("Office_OfficeDataGrid_DeleteAdress", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Office_OfficeDataGrid_RefreshAdress {
            get {
                return ResourceManager.GetString("Office_OfficeDataGrid_RefreshAdress", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string Office_OfficeEquipmentGridBlock_CreateOfficeEquipment {
            get {
                return ResourceManager.GetString("Office_OfficeEquipmentGridBlock_CreateOfficeEquipment", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string Office_OfficeEquipmentGridBlock_EditOfficeEquipment {
            get {
                return ResourceManager.GetString("Office_OfficeEquipmentGridBlock_EditOfficeEquipment", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Office_OfficeEquipmentGridBlock_DeleteOfficeEquipment {
            get {
                return ResourceManager.GetString("Office_OfficeEquipmentGridBlock_DeleteOfficeEquipment", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Office_OfficeEquipmentGridBlock_RefreshOfficeEquipment {
            get {
                return ResourceManager.GetString("Office_OfficeEquipmentGridBlock_RefreshOfficeEquipment", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Создать....
        /// </summary>
        public static string Office_OfficeEmployees_CreateOfficeEmployee {
            get {
                return ResourceManager.GetString("Office_OfficeEmployees_CreateOfficeEmployee", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить....
        /// </summary>
        public static string Office_OfficeEmployees_EditOfficeEmployee {
            get {
                return ResourceManager.GetString("Office_OfficeEmployees_EditOfficeEmployee", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить....
        /// </summary>
        public static string Office_OfficeEmployees_DeleteOfficeEmployee {
            get {
                return ResourceManager.GetString("Office_OfficeEmployees_DeleteOfficeEmployee", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string Office_OfficeEmployees_RefreshOfficeEmployee {
            get {
                return ResourceManager.GetString("Office_OfficeEmployees_RefreshOfficeEmployee", resourceCulture);
            }
		}
        
        
    }
}