//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karelia.WebAPI.Controllers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScreenResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScreenResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karelia.WebAPI.Controllers.Properties.ScreenResources", typeof(ScreenResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модели.
        /// </summary>
        public static string CarModels_DisplayName {
            get {
                return ResourceManager.GetString("CarModels_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные детали.
        /// </summary>
        public static string CarModels_CarModelParts {
            get {
                return ResourceManager.GetString("CarModels_CarModelParts", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        public static string CarModels_CarModels_Name {
            get {
                return ResourceManager.GetString("CarModels_CarModels_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Расход топлива.
        /// </summary>
        public static string CarModels_CarModels_FuelConsumption {
            get {
                return ResourceManager.GetString("CarModels_CarModels_FuelConsumption", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь.
        /// </summary>
        public static string CarModels_CarModelPart_Name {
            get {
                return ResourceManager.GetString("CarModels_CarModelPart_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string CarModels_CarModelPart_Price {
            get {
                return ResourceManager.GetString("CarModels_CarModelPart_Price", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Машины.
        /// </summary>
        public static string Cars_DisplayName {
            get {
                return ResourceManager.GetString("Cars_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ремонты.
        /// </summary>
        public static string Cars_Visits {
            get {
                return ResourceManager.GetString("Cars_Visits", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        public static string Cars_CarsGridBlock_CarModel_Name {
            get {
                return ResourceManager.GetString("Cars_CarsGridBlock_CarModel_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Госномер.
        /// </summary>
        public static string Cars_CarsGridBlock_Number {
            get {
                return ResourceManager.GetString("Cars_CarsGridBlock_Number", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Cars_CarsGridBlock_Description {
            get {
                return ResourceManager.GetString("Cars_CarsGridBlock_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Расход топлива.
        /// </summary>
        public static string Cars_CarsGridBlock_CarModel_FuelConsumption {
            get {
                return ResourceManager.GetString("Cars_CarsGridBlock_CarModel_FuelConsumption", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Приезд.
        /// </summary>
        public static string Cars_CarServiceDataGrid_StartDate {
            get {
                return ResourceManager.GetString("Cars_CarServiceDataGrid_StartDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Конец ремонта.
        /// </summary>
        public static string Cars_CarServiceDataGrid_EndDate {
            get {
                return ResourceManager.GetString("Cars_CarServiceDataGrid_EndDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Пробег.
        /// </summary>
        public static string Cars_CarServiceDataGrid_Odometer {
            get {
                return ResourceManager.GetString("Cars_CarServiceDataGrid_Odometer", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Причина приезда.
        /// </summary>
        public static string Cars_CarServiceDataGrid_CarArrivalReasonType_Name {
            get {
                return ResourceManager.GetString("Cars_CarServiceDataGrid_CarArrivalReasonType_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь.
        /// </summary>
        public static string Cars_CarServicePart_CarModelPart_Name {
            get {
                return ResourceManager.GetString("Cars_CarServicePart_CarModelPart_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Cars_CarServicePart_CarModelPart_Price {
            get {
                return ResourceManager.GetString("Cars_CarServicePart_CarModelPart_Price", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        public static string Cars_CarServicePart_Quantity {
            get {
                return ResourceManager.GetString("Cars_CarServicePart_Quantity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Тип работы.
        /// </summary>
        public static string Cars_CarServiceWork_CarWorkType_Name {
            get {
                return ResourceManager.GetString("Cars_CarServiceWork_CarWorkType_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ремонты.
        /// </summary>
        public static string Works_DisplayName {
            get {
                return ResourceManager.GetString("Works_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        public static string Works_Cars_CarModel_Name {
            get {
                return ResourceManager.GetString("Works_Cars_CarModel_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Госномер.
        /// </summary>
        public static string Works_Cars_Number {
            get {
                return ResourceManager.GetString("Works_Cars_Number", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Works_Cars_Description {
            get {
                return ResourceManager.GetString("Works_Cars_Description", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Расход топлива.
        /// </summary>
        public static string Works_Cars_CarModel_FuelConsumption {
            get {
                return ResourceManager.GetString("Works_Cars_CarModel_FuelConsumption", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Приезд.
        /// </summary>
        public static string Works_Services_StartDate {
            get {
                return ResourceManager.GetString("Works_Services_StartDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Конец ремонта.
        /// </summary>
        public static string Works_Services_EndDate {
            get {
                return ResourceManager.GetString("Works_Services_EndDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Причина приезда.
        /// </summary>
        public static string Works_Services_CarArrivalReasonType_Name {
            get {
                return ResourceManager.GetString("Works_Services_CarArrivalReasonType_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Пробег.
        /// </summary>
        public static string Works_Services_Odometer {
            get {
                return ResourceManager.GetString("Works_Services_Odometer", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Жалоба.
        /// </summary>
        public static string Works_Services_Defect {
            get {
                return ResourceManager.GetString("Works_Services_Defect", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Вывод.
        /// </summary>
        public static string Works_Services_Conclusion {
            get {
                return ResourceManager.GetString("Works_Services_Conclusion", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Задачи.
        /// </summary>
        public static string Tasks_DisplayName {
            get {
                return ResourceManager.GetString("Tasks_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнено .
        /// </summary>
        public static string Tasks_MainTaskGrid_IsCompleted {
            get {
                return ResourceManager.GetString("Tasks_MainTaskGrid_IsCompleted", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Задача.
        /// </summary>
        public static string Tasks_MainTaskGrid_Name {
            get {
                return ResourceManager.GetString("Tasks_MainTaskGrid_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string Tasks_MainTaskGrid_CreationDate {
            get {
                return ResourceManager.GetString("Tasks_MainTaskGrid_CreationDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Сроки .
        /// </summary>
        public static string Tasks_MainTaskGrid_EndDate {
            get {
                return ResourceManager.GetString("Tasks_MainTaskGrid_EndDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ответсвенный.
        /// </summary>
        public static string Tasks_MainTaskGrid_Employee_Name {
            get {
                return ResourceManager.GetString("Tasks_MainTaskGrid_Employee_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Порядок.
        /// </summary>
        public static string Tasks_SubTaskGrid_Sequence {
            get {
                return ResourceManager.GetString("Tasks_SubTaskGrid_Sequence", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Подзадача.
        /// </summary>
        public static string Tasks_SubTaskGrid_Name {
            get {
                return ResourceManager.GetString("Tasks_SubTaskGrid_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модели оргтехники.
        /// </summary>
        public static string ModelEquipments_DisplayName {
            get {
                return ResourceManager.GetString("ModelEquipments_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель оборудования.
        /// </summary>
        public static string ModelEquipments_ModelEquipmentGrid_Name {
            get {
                return ResourceManager.GetString("ModelEquipments_ModelEquipmentGrid_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Офисы.
        /// </summary>
        public static string Office_DisplayName {
            get {
                return ResourceManager.GetString("Office_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Оргтехника.
        /// </summary>
        public static string Office_OfficeEquipment {
            get {
                return ResourceManager.GetString("Office_OfficeEquipment", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудники.
        /// </summary>
        public static string Office_Employees {
            get {
                return ResourceManager.GetString("Office_Employees", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string Office_OfficeDataGrid_Adress {
            get {
                return ResourceManager.GetString("Office_OfficeDataGrid_Adress", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Инвентарный номер.
        /// </summary>
        public static string Office_OfficeEquipmentGridBlock_InventoryNumber {
            get {
                return ResourceManager.GetString("Office_OfficeEquipmentGridBlock_InventoryNumber", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        public static string Office_OfficeEquipmentGridBlock_OfficeEquipmentModel_Name {
            get {
                return ResourceManager.GetString("Office_OfficeEquipmentGridBlock_OfficeEquipmentModel_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Дата размещения.
        /// </summary>
        public static string Office_OfficeEquipmentGridBlock_PlacementDate {
            get {
                return ResourceManager.GetString("Office_OfficeEquipmentGridBlock_PlacementDate", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        public static string Office_OfficeEquipmentGridBlock_Quontity {
            get {
                return ResourceManager.GetString("Office_OfficeEquipmentGridBlock_Quontity", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ответственный.
        /// </summary>
        public static string Office_OfficeEquipmentGridBlock_OfiiceEmployee_Name {
            get {
                return ResourceManager.GetString("Office_OfficeEquipmentGridBlock_OfiiceEmployee_Name", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудник.
        /// </summary>
        public static string Office_OfficeEmployees_Name {
            get {
                return ResourceManager.GetString("Office_OfficeEmployees_Name", resourceCulture);
            }
		}
        
        
    }
}