//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karelia.WebAPI.Controllers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karelia.WebAPI.Controllers.Properties.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUserPermissionsDisplayView_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUserPermissionsDisplayView_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUserPermissionsDisplayView_PermissionId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUserPermissionsDisplayView_PermissionId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperation_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperation_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperation_UserID_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperation_UserID_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperation_Date_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperation_Date_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperation_ActionId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperation_ActionId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperation_OperationResultId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperation_OperationResultId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarWorkType_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("CarWorkType_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_ParentId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_ParentId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_ClassId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_ClassId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_CodeName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_CodeName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_DisplayName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_DisplayName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObject_Guid_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObject_Guid_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationResult_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationResult_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationResult_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationResult_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Office_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Office_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Office_Adress_RequiredMsg {
            get {
                return ResourceManager.GetString("Office_Adress_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarArrivalReasonType_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("CarArrivalReasonType_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarArrivalReasonType_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("CarArrivalReasonType_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_Token_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_Token_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_ValidFrom_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_ValidFrom_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysResetPasswordToken_IsExecuted_RequiredMsg {
            get {
                return ResourceManager.GetString("SysResetPasswordToken_IsExecuted_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRefreshToken_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRefreshToken_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRefreshToken_ClientId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRefreshToken_ClientId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRefreshToken_Token_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRefreshToken_Token_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRefreshToken_ExpiresUtc_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRefreshToken_ExpiresUtc_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_IsOwnByUser_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_IsOwnByUser_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRole_IsSystem_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRole_IsSystem_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_AccountName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_AccountName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_DisplayName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_DisplayName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_IsDeactivated_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_IsDeactivated_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_IsSystemUser_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_IsSystemUser_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_FullAccess_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_FullAccess_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_IsEmailConfirmed_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_IsEmailConfirmed_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_IsAnonymous_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_IsAnonymous_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUser_CreateDate_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUser_CreateDate_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarServiceWork_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("CarServiceWork_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarServiceWork_CarServiceId_RequiredMsg {
            get {
                return ResourceManager.GetString("CarServiceWork_CarServiceId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarServiceWork_CarWorkTypeId_RequiredMsg {
            get {
                return ResourceManager.GetString("CarServiceWork_CarWorkTypeId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRolePermission_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRolePermission_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRolePermission_RoleId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRolePermission_RoleId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysRolePermission_PermissionId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysRolePermission_PermissionId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Car_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("Car_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Car_CarModelId_RequiredMsg {
            get {
                return ResourceManager.GetString("Car_CarModelId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Car_Number_RequiredMsg {
            get {
                return ResourceManager.GetString("Car_Number_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubTask_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SubTask_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubTask_TaskId_RequiredMsg {
            get {
                return ResourceManager.GetString("SubTask_TaskId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubTask_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SubTask_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarModelPart_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("CarModelPart_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarModelPart_CarModelId_RequiredMsg {
            get {
                return ResourceManager.GetString("CarModelPart_CarModelId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarModelPart_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("CarModelPart_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_OperationName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_OperationContext_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_OperationContext_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_AquiredTime_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_AquiredTime_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysOperationLock_ExpirationTime_RequiredMsg {
            get {
                return ResourceManager.GetString("SysOperationLock_ExpirationTime_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUserRole_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUserRole_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUserRole_UserId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUserRole_UserId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUserRole_RoleId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUserRole_RoleId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarService_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("CarService_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarService_CarId_RequiredMsg {
            get {
                return ResourceManager.GetString("CarService_CarId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfiiceEmployee_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("OfiiceEmployee_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfiiceEmployee_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("OfiiceEmployee_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfiiceEmployee_OfficeId_RequiredMsg {
            get {
                return ResourceManager.GetString("OfiiceEmployee_OfficeId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermission_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermission_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermission_Type_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermission_Type_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermission_CodeName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermission_CodeName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermission_ObjectId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermission_ObjectId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermission_Guid_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermission_Guid_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSetting_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSetting_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSetting_SettingPropertyId_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSetting_SettingPropertyId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainTask_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("MainTask_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainTask_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("MainTask_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainTask_EmployeeId_RequiredMsg {
            get {
                return ResourceManager.GetString("MainTask_EmployeeId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainTask_IsCompleted_RequiredMsg {
            get {
                return ResourceManager.GetString("MainTask_IsCompleted_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeEquipment_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("OfficeEquipment_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeEquipment_OfficeId_RequiredMsg {
            get {
                return ResourceManager.GetString("OfficeEquipment_OfficeId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeEquipment_OfficeEquipmentModelId_RequiredMsg {
            get {
                return ResourceManager.GetString("OfficeEquipment_OfficeEquipmentModelId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeEquipment_InventoryNumber_RequiredMsg {
            get {
                return ResourceManager.GetString("OfficeEquipment_InventoryNumber_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeEquipment_OfficeEmployeeId_RequiredMsg {
            get {
                return ResourceManager.GetString("OfficeEquipment_OfficeEmployeeId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysInfo_SystemVersion_RequiredMsg {
            get {
                return ResourceManager.GetString("SysInfo_SystemVersion_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysInfo_DomainVersion_RequiredMsg {
            get {
                return ResourceManager.GetString("SysInfo_DomainVersion_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysInfo_LastInitialization_RequiredMsg {
            get {
                return ResourceManager.GetString("SysInfo_LastInitialization_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarServicePart_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("CarServicePart_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarServicePart_CarServiceId_RequiredMsg {
            get {
                return ResourceManager.GetString("CarServicePart_CarServiceId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarServicePart_CarModelPartId_RequiredMsg {
            get {
                return ResourceManager.GetString("CarServicePart_CarModelPartId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarServicePart_Quantity_RequiredMsg {
            get {
                return ResourceManager.GetString("CarServicePart_Quantity_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObjectType_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObjectType_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObjectType_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObjectType_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MethodicalToolkit_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("MethodicalToolkit_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MethodicalToolkit_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("MethodicalToolkit_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObjectClass_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObjectClass_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObjectClass_CodeName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObjectClass_CodeName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysObjectClass_DisplayName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysObjectClass_DisplayName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermissionType_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermissionType_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermissionType_CodeName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermissionType_CodeName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysPermissionType_DisplayName_RequiredMsg {
            get {
                return ResourceManager.GetString("SysPermissionType_DisplayName_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_IsManaged_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsManaged_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysSettingProperty_IsOverridable_RequiredMsg {
            get {
                return ResourceManager.GetString("SysSettingProperty_IsOverridable_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SysUsersDisplayView_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("SysUsersDisplayView_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarModel_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("CarModel_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarModel_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("CarModel_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MethodicalToolkitFile_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("MethodicalToolkitFile_Id_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MethodicalToolkitFile_MethodicalToolkitId_RequiredMsg {
            get {
                return ResourceManager.GetString("MethodicalToolkitFile_MethodicalToolkitId_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MethodicalToolkitFile_Name_RequiredMsg {
            get {
                return ResourceManager.GetString("MethodicalToolkitFile_Name_RequiredMsg", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeEquipmentModel_Id_RequiredMsg {
            get {
                return ResourceManager.GetString("OfficeEquipmentModel_Id_RequiredMsg", resourceCulture);
            }
		}
        
        
    }
}