//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karelia.WebAPI.Controllers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WizardResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WizardResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karelia.WebAPI.Controllers.Properties.WizardResources", typeof(WizardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авто.
        /// </summary>
        public static string CarWizard_CarPage {
            get {
                return ResourceManager.GetString("CarWizard_CarPage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Авто.
        /// </summary>
        public static string CarWizard_CarPage_BannerTitle {
            get {
                return ResourceManager.GetString("CarWizard_CarPage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarWizard_CarPage_BannerDescription {
            get {
                return ResourceManager.GetString("CarWizard_CarPage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Госномер.
        /// </summary>
        public static string CarWizard_CarPage_Number_DisplayName {
            get {
                return ResourceManager.GetString("CarWizard_CarPage_Number_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string CarWizard_CarPage_Description_DisplayName {
            get {
                return ResourceManager.GetString("CarWizard_CarPage_Description_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        public static string CarWizard_CarPage_CarModelId_DisplayName {
            get {
                return ResourceManager.GetString("CarWizard_CarPage_CarModelId_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель авто.
        /// </summary>
        public static string CarModelWizard_CarModelPage {
            get {
                return ResourceManager.GetString("CarModelWizard_CarModelPage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель авто.
        /// </summary>
        public static string CarModelWizard_CarModelPage_BannerTitle {
            get {
                return ResourceManager.GetString("CarModelWizard_CarModelPage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarModelWizard_CarModelPage_BannerDescription {
            get {
                return ResourceManager.GetString("CarModelWizard_CarModelPage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель.
        /// </summary>
        public static string CarModelWizard_CarModelPage_Name_DisplayName {
            get {
                return ResourceManager.GetString("CarModelWizard_CarModelPage_Name_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Расход топлива.
        /// </summary>
        public static string CarModelWizard_CarModelPage_FuelConsumption_DisplayName {
            get {
                return ResourceManager.GetString("CarModelWizard_CarModelPage_FuelConsumption_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь для машины.
        /// </summary>
        public static string CarModelPartWizard_CarModelPartPage {
            get {
                return ResourceManager.GetString("CarModelPartWizard_CarModelPartPage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь для машины.
        /// </summary>
        public static string CarModelPartWizard_CarModelPartPage_BannerTitle {
            get {
                return ResourceManager.GetString("CarModelPartWizard_CarModelPartPage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarModelPartWizard_CarModelPartPage_BannerDescription {
            get {
                return ResourceManager.GetString("CarModelPartWizard_CarModelPartPage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь.
        /// </summary>
        public static string CarModelPartWizard_CarModelPartPage_Name_DisplayName {
            get {
                return ResourceManager.GetString("CarModelPartWizard_CarModelPartPage_Name_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string CarModelPartWizard_CarModelPartPage_Price_DisplayName {
            get {
                return ResourceManager.GetString("CarModelPartWizard_CarModelPartPage_Price_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обслуживание.
        /// </summary>
        public static string CarServiceWizard_CarServicePage {
            get {
                return ResourceManager.GetString("CarServiceWizard_CarServicePage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Обслуживание.
        /// </summary>
        public static string CarServiceWizard_CarServicePage_BannerTitle {
            get {
                return ResourceManager.GetString("CarServiceWizard_CarServicePage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarServiceWizard_CarServicePage_BannerDescription {
            get {
                return ResourceManager.GetString("CarServiceWizard_CarServicePage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Приезд.
        /// </summary>
        public static string CarServiceWizard_CarServicePage_StartDate_DisplayName {
            get {
                return ResourceManager.GetString("CarServiceWizard_CarServicePage_StartDate_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Конец ремонта.
        /// </summary>
        public static string CarServiceWizard_CarServicePage_EndDate_DisplayName {
            get {
                return ResourceManager.GetString("CarServiceWizard_CarServicePage_EndDate_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Пробег.
        /// </summary>
        public static string CarServiceWizard_CarServicePage_Odometer_DisplayName {
            get {
                return ResourceManager.GetString("CarServiceWizard_CarServicePage_Odometer_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Жалоба.
        /// </summary>
        public static string CarServiceWizard_CarServicePage_Defect_DisplayName {
            get {
                return ResourceManager.GetString("CarServiceWizard_CarServicePage_Defect_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Вывод.
        /// </summary>
        public static string CarServiceWizard_CarServicePage_Conclusion_DisplayName {
            get {
                return ResourceManager.GetString("CarServiceWizard_CarServicePage_Conclusion_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Причина приезда.
        /// </summary>
        public static string CarServiceWizard_CarServicePage_CarArrivalReasonTypeId_DisplayName {
            get {
                return ResourceManager.GetString("CarServiceWizard_CarServicePage_CarArrivalReasonTypeId_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь для ремонта.
        /// </summary>
        public static string CarServicePartWizard_CarServicePartPage {
            get {
                return ResourceManager.GetString("CarServicePartWizard_CarServicePartPage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь для ремонта.
        /// </summary>
        public static string CarServicePartWizard_CarServicePartPage_BannerTitle {
            get {
                return ResourceManager.GetString("CarServicePartWizard_CarServicePartPage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarServicePartWizard_CarServicePartPage_BannerDescription {
            get {
                return ResourceManager.GetString("CarServicePartWizard_CarServicePartPage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        public static string CarServicePartWizard_CarServicePartPage_Quantity_DisplayName {
            get {
                return ResourceManager.GetString("CarServicePartWizard_CarServicePartPage_Quantity_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Деталь.
        /// </summary>
        public static string CarServicePartWizard_CarServicePartPage_CarModelPartId_DisplayName {
            get {
                return ResourceManager.GetString("CarServicePartWizard_CarServicePartPage_CarModelPartId_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ремонтная работа.
        /// </summary>
        public static string CarServiceWorkWizard_CarServiceWorkPage {
            get {
                return ResourceManager.GetString("CarServiceWorkWizard_CarServiceWorkPage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ремонтная работа.
        /// </summary>
        public static string CarServiceWorkWizard_CarServiceWorkPage_BannerTitle {
            get {
                return ResourceManager.GetString("CarServiceWorkWizard_CarServiceWorkPage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CarServiceWorkWizard_CarServiceWorkPage_BannerDescription {
            get {
                return ResourceManager.GetString("CarServiceWorkWizard_CarServiceWorkPage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string CarServiceWorkWizard_CarServiceWorkPage_Comments_DisplayName {
            get {
                return ResourceManager.GetString("CarServiceWorkWizard_CarServiceWorkPage_Comments_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Тип работы.
        /// </summary>
        public static string CarServiceWorkWizard_CarServiceWorkPage_CarWorkTypeId_DisplayName {
            get {
                return ResourceManager.GetString("CarServiceWorkWizard_CarServiceWorkPage_CarWorkTypeId_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Основная задача.
        /// </summary>
        public static string MainTaskWizard_MainTaskPage {
            get {
                return ResourceManager.GetString("MainTaskWizard_MainTaskPage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Основная задача.
        /// </summary>
        public static string MainTaskWizard_MainTaskPage_BannerTitle {
            get {
                return ResourceManager.GetString("MainTaskWizard_MainTaskPage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MainTaskWizard_MainTaskPage_BannerDescription {
            get {
                return ResourceManager.GetString("MainTaskWizard_MainTaskPage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Задача.
        /// </summary>
        public static string MainTaskWizard_MainTaskPage_Name_DisplayName {
            get {
                return ResourceManager.GetString("MainTaskWizard_MainTaskPage_Name_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ответсвенный.
        /// </summary>
        public static string MainTaskWizard_MainTaskPage_EmployeeId_DisplayName {
            get {
                return ResourceManager.GetString("MainTaskWizard_MainTaskPage_EmployeeId_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string MainTaskWizard_MainTaskPage_CreationDate_DisplayName {
            get {
                return ResourceManager.GetString("MainTaskWizard_MainTaskPage_CreationDate_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Сроки.
        /// </summary>
        public static string MainTaskWizard_MainTaskPage_EndDate_DisplayName {
            get {
                return ResourceManager.GetString("MainTaskWizard_MainTaskPage_EndDate_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string MainTaskWizard_MainTaskPage_Comments_DisplayName {
            get {
                return ResourceManager.GetString("MainTaskWizard_MainTaskPage_Comments_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнено.
        /// </summary>
        public static string MainTaskWizard_MainTaskPage_IsCompleted_DisplayName {
            get {
                return ResourceManager.GetString("MainTaskWizard_MainTaskPage_IsCompleted_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Подзадача.
        /// </summary>
        public static string SubTaskWizard_SubTaskPage {
            get {
                return ResourceManager.GetString("SubTaskWizard_SubTaskPage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Подзадача.
        /// </summary>
        public static string SubTaskWizard_SubTaskPage_BannerTitle {
            get {
                return ResourceManager.GetString("SubTaskWizard_SubTaskPage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SubTaskWizard_SubTaskPage_BannerDescription {
            get {
                return ResourceManager.GetString("SubTaskWizard_SubTaskPage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Подзадача.
        /// </summary>
        public static string SubTaskWizard_SubTaskPage_Name_DisplayName {
            get {
                return ResourceManager.GetString("SubTaskWizard_SubTaskPage_Name_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Порядок.
        /// </summary>
        public static string SubTaskWizard_SubTaskPage_Sequence_DisplayName {
            get {
                return ResourceManager.GetString("SubTaskWizard_SubTaskPage_Sequence_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string SubTaskWizard_SubTaskPage_Description_DisplayName {
            get {
                return ResourceManager.GetString("SubTaskWizard_SubTaskPage_Description_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Офис.
        /// </summary>
        public static string OfficeWizard_OfficePage {
            get {
                return ResourceManager.GetString("OfficeWizard_OfficePage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Офис.
        /// </summary>
        public static string OfficeWizard_OfficePage_BannerTitle {
            get {
                return ResourceManager.GetString("OfficeWizard_OfficePage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeWizard_OfficePage_BannerDescription {
            get {
                return ResourceManager.GetString("OfficeWizard_OfficePage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string OfficeWizard_OfficePage_Adress_DisplayName {
            get {
                return ResourceManager.GetString("OfficeWizard_OfficePage_Adress_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Оргтехника.
        /// </summary>
        public static string OfficeEquipmentWizard_OfficeEquipmentPage {
            get {
                return ResourceManager.GetString("OfficeEquipmentWizard_OfficeEquipmentPage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Оргтехника.
        /// </summary>
        public static string OfficeEquipmentWizard_OfficeEquipmentPage_BannerTitle {
            get {
                return ResourceManager.GetString("OfficeEquipmentWizard_OfficeEquipmentPage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeEquipmentWizard_OfficeEquipmentPage_BannerDescription {
            get {
                return ResourceManager.GetString("OfficeEquipmentWizard_OfficeEquipmentPage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель оборудования.
        /// </summary>
        public static string OfficeEquipmentWizard_OfficeEquipmentPage_OfficeEquipmentModelId_DisplayName {
            get {
                return ResourceManager.GetString("OfficeEquipmentWizard_OfficeEquipmentPage_OfficeEquipmentModelId_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Инвентарный номер.
        /// </summary>
        public static string OfficeEquipmentWizard_OfficeEquipmentPage_InventoryNumber_DisplayName {
            get {
                return ResourceManager.GetString("OfficeEquipmentWizard_OfficeEquipmentPage_InventoryNumber_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Дата размещения.
        /// </summary>
        public static string OfficeEquipmentWizard_OfficeEquipmentPage_PlacementDate_DisplayName {
            get {
                return ResourceManager.GetString("OfficeEquipmentWizard_OfficeEquipmentPage_PlacementDate_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string OfficeEquipmentWizard_OfficeEquipmentPage_Description_DisplayName {
            get {
                return ResourceManager.GetString("OfficeEquipmentWizard_OfficeEquipmentPage_Description_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        public static string OfficeEquipmentWizard_OfficeEquipmentPage_Quontity_DisplayName {
            get {
                return ResourceManager.GetString("OfficeEquipmentWizard_OfficeEquipmentPage_Quontity_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Ответственный.
        /// </summary>
        public static string OfficeEquipmentWizard_OfficeEquipmentPage_OfficeEmployeeId_DisplayName {
            get {
                return ResourceManager.GetString("OfficeEquipmentWizard_OfficeEquipmentPage_OfficeEmployeeId_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудник.
        /// </summary>
        public static string OfficeEmployeeWizard_OfficeEmployeePage {
            get {
                return ResourceManager.GetString("OfficeEmployeeWizard_OfficeEmployeePage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудник.
        /// </summary>
        public static string OfficeEmployeeWizard_OfficeEmployeePage_BannerTitle {
            get {
                return ResourceManager.GetString("OfficeEmployeeWizard_OfficeEmployeePage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeEmployeeWizard_OfficeEmployeePage_BannerDescription {
            get {
                return ResourceManager.GetString("OfficeEmployeeWizard_OfficeEmployeePage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Сотрудник.
        /// </summary>
        public static string OfficeEmployeeWizard_OfficeEmployeePage_Name_DisplayName {
            get {
                return ResourceManager.GetString("OfficeEmployeeWizard_OfficeEmployeePage_Name_DisplayName", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель оборудования.
        /// </summary>
        public static string OfficeEquipmentModelWizard_EquipmentModelPage {
            get {
                return ResourceManager.GetString("OfficeEquipmentModelWizard_EquipmentModelPage", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель оборудования.
        /// </summary>
        public static string OfficeEquipmentModelWizard_EquipmentModelPage_BannerTitle {
            get {
                return ResourceManager.GetString("OfficeEquipmentModelWizard_EquipmentModelPage_BannerTitle", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OfficeEquipmentModelWizard_EquipmentModelPage_BannerDescription {
            get {
                return ResourceManager.GetString("OfficeEquipmentModelWizard_EquipmentModelPage_BannerDescription", resourceCulture);
            }
		}
        
        /// <summary>
        ///   Looks up a localized string similar to Модель оборудования.
        /// </summary>
        public static string OfficeEquipmentModelWizard_EquipmentModelPage_Name_DisplayName {
            get {
                return ResourceManager.GetString("OfficeEquipmentModelWizard_EquipmentModelPage_Name_DisplayName", resourceCulture);
            }
		}
        
        
    }
}